### ISSUE TITLE
how to set test/staging mode？

### ISSUE THREAD

**Issue by wulucxy** [survivejs-demos/webpack-demo#10]
Hi，@bebraw，thanks a hot for the project！

I have a question，I have 4 development env now：

- development：for developer use only
- test：for qa to find bug of the app
- staging：mimic the production env to double check the quality of app
- production：for users

I can understand the mode setting for *development* and *production*，and also *staging*，because *staging* should always the same with *production*

but how to set *test* mode，it seems *development* and *production* are both not right。

what I need *test* env is：

- different publicpath
- sourcemap
- no uglify
- split chunks
- contenthash

so，do you gave me some guide or docs？thanks a lot！！

**Comment by bebraw** [comment]
Did you find a good solution for this?

I would follow a combination of setting `NODE_ENV` at **package.json** scripts and using webpack `--env` to control which configuration it's going to pick. For environment variables, I've found [dotenv](https://www.npmjs.com/package/dotenv) to be useful and you can use it with webpack through [dotenv-webpack](https://www.npmjs.com/package/dotenv-webpack).

I explain the composition approach [here](https://survivejs.com/webpack/developing/composing-configuration/).
