### ISSUE TITLE
purifycss-webpack-plugin craps out the styling

### ISSUE THREAD

**Issue by rohans84** [survivejs-demos/webpack-demo#2]
Using purifycss-webpack-plugin removes the styling applied by PureCSS library. Running the build example on browser - the button 'Hello World' text is no longer visible.  On investigating the generated style.[hash].css, I could not find the required css classes defined. Not sure if this is issue with plugin (or version) or the configuration.

I am able to see the button class correctly applied in dev server mode

My versions used:
Webpack: 2.1.0-beta.28
PurifyCSS  plugin: 2.0.3
Node: 7.0.0

**Comment by bebraw** [comment]
Solved as discussed in #3.
