### ISSUE TITLE
provide an example to use it in project (via npm)

### ISSUE THREAD

**Issue by aladdin-add** [survivejs-demos/webpack-demo#4]

**Comment by bebraw** [comment]
Hi,

It's not meant to be consumed through npm directly. It's more like a source for ideas. Please see the book online for more specific explanations. :)

**Comment by aladdin-add** [comment]
I do like compose webpack config in this way, and want to use `webpack.parts.js` for my own config. But seems like it's not in the package. can we publish it?

**Comment by bebraw** [comment]
@Aladdin-ADD You could publish it on your own. A [scoped package](https://docs.npmjs.com/misc/scope) might work nicely.

Time to close this one. :)
