### ISSUE TITLE
is there a plan to support webpack v3+?

### ISSUE THREAD

**Issue by aladdin-add** [survivejs-demos/webpack-demo#5]
![image](https://user-images.githubusercontent.com/13050025/30552246-e8aa83de-9ccf-11e7-8397-aa31f6957044.png)

**Comment by bebraw** [comment]
Hi,

It should work with webpack 3 after a simple dependency upgrade. There's nothing breaking.

To get rid of the error you might have to reinstall `node_modules`.

I'll update the demo when I rework the book (likely for webpack 4).
