### ISSUE TITLE
where can I find the multi-compiler mode source code in SSR part?

### ISSUE THREAD

**Issue by wulucxy** [survivejs-demos/webpack-demo#9]
1. where can I find the multi-compiler mode source code in SSR part?
```
Even though there is a React application running now, it's difficult to develop. If you try to modify the code, nothing happens. The problem can be solved running webpack in a **multi-compiler mode** as earlier in this book. Another option is to run webpack in watch mode against the current configuration and set up a watcher for the server. You'll learn the setup next.
```

2.  what do you mean by  through something else other than Node？

```
How to run the server through something else other than Node? One option would be to wrap the Node instance in a service you then run through your host environment. Ideally, the results would be cached, and you can find more specific solutions for this particular per platform.
```

**Comment by bebraw** [comment]
> where can I find the multi-compiler mode source code in SSR part?

It's a feature of webpack activated by returning an array of configurations. Webpack will compile each separately. I think I'll clarify this when closing the issue.

> what do you mean by through something else other than Node？

Think Java and such. I think I'll add some examples to the paragraph.

Sorry for the late reply. It was a busy end of the year.

**Comment by bebraw** [comment]
I added more specific info. Time to close. 👍
